version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"  # Map host port 4000 to container port 4000
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongodb:27017/mydatabase  # Use 'mongodb' as the hostname
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongodb-data:/data/db/  # Persist data

volumes:
  mongodb-data:
